server:
  port: 8085
spring:
  application:
    name: foreign-center
  datasource:
    url: jdbc:mysql://192.168.1.34:3306/dev_book_foreign?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: grl_admin
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 10
      max-active: 20
      test-on-borrow: true
      test-while-idle: true
  data:
    solr:
      host: http://192.168.1.34:8989/solr/
      solruser: solr
      password: SolrRocks
  redis:
    host: 47.110.154.181
    port: 6379
    password: book2018@redis
    database: 12
    timeout: 60000ms
    shiro-timeout: 60000
#    jedis:
#      pool:
#        max-active: 20
#        max-wait: -1ms
#        max-idle: 20
#        min-idle: 0
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/
feign:
  hystrix:
    enabled: true

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.springcloud.book.foreign.domain;com.springcloud.book.foreign.config
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      column-like: true
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
#关闭solr自带的安全验证
management:
  health:
    solr:
      enabled: false
#logging
logging:
  level:
    root: INFO
    com.book: INFO
  file: logs/service-handling.log