server:
  port: 8003
spring:
  application:
    name: email-center
  datasource:
    url: jdbc:mysql://192.168.1.112:3306/test_book_foreign?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: bookUser
    password: bookUserBook2018
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 10
      max-active: 20
      test-on-borrow: true
      test-while-idle: true
      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.springcloud.book.emailsystem.domain
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      column-like: true
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

#logging
logging:
  level:
    root: INFO
    com.book: INFO
  file: logs/service-handling.log